version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crilstats
    ports:
      - "5432:5432"
