name: Sync Tool Branches with Main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Notebook to HTML and Sync to data-analysis branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Checkout data-analysis branch and clean up previous contents
          git checkout -B data-analysis
          git rm -r --ignore-unmatch '*'

          # Copy playbook.ipynb from main branch
          git checkout main -- ./playbook.ipynb
          jupyter nbconvert --to html playbook.ipynb

          # Add and commit playbook files
          git add playbook.ipynb playbook.html
          git commit -m "Update playbook.ipynb and generate HTML from main"
          git push origin data-analysis --force

      - name: Sync CrilScrapper branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Checkout scrapper branch and clean up previous contents
          git checkout -B scrapper
          git rm -r --ignore-unmatch '*'

          # Copy CrilScrapper contents from main branch
          git checkout main -- ./CrilScrapper

          # Add and commit CrilScrapper files
          git add ./CrilScrapper
          git commit -m "Update CrilScrapper from main"
          git push origin scrapper --force
